title: 心言自由(XinYaanZyoy)
logo: logo.jpeg
email: XinYaanZyoy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  👊hola!🙂
  I'm 心言自由 (XinYaanZyoy), 
  I do only 3 things; AI, QG, and ET!
  I'm a metaphysicist;
  engineering is my livelihood;
  computer science is my hobby;
  meet my wife; mathematics, brothers; physics and philosophy, sisters; music, linguistics, arts and biology!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://XinYaanZyoy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: XinYaanZyoy
github_username:  XinYaanZyoy

resume:
  demo: false
  photo: "https://raw.githubusercontent.com/AstroSpaceTech/AstroSpaceTech.github.io/master/assets/images/avatars/XinYaanZyoy.jpg"
  name: "Parth Patel (XinYaanZyoy)"
  copy: "I'm a metaphysicist, that is the mathematics and philosophy of metaphysical objects, also study physics, mathematics, philosophy, astronomy, computer science, technologies, and engineering!"
  # Color scheme based on http://www.materialui.co/colors.
  # Possible values:
  # - default
  # - red
  # - pink
  # - brown
  # - blue
  # - purple
  # - teal
  # - green
  color: purple
  cards:
    
    #   - type:
    #     heding:
    #     subheading:
    #     duration:
    #     location:
    #     content:
    
    - type: Physics
      heading: QM
      subheading: Old Quantum theory
      duration: 2017-2018
      content: our physics mam gave me a chance to give 1.5 hrs lec on the transition from Old Quantum theory to New Quantum theory
    - type: Mathematics
      heading: Linear Algebra
      duration: 2017-2018
      subheading: A playscript on ODEs and LA
      content: i wrote this 80 pages long play script to discuss about the ODES in basic forms
    - type: Philosophy
      heading: Bhagwad Gita
      subheading: the power of gita
      content: i wrote a short note on what gives the power to gita according to my understanding
    - type: Astronomy
      heading: Start Up
      duration: 2019-present
      subheading: AstroSpacetech.in
      content: i cofounded this startup in which we write articles on Astronomy, Space Sciene, And Technologies and planning to organize events and workshops for scholl students
    - type: Computer Science.
      heading: Software Pipeline
      subheading: Xbooks
      duration: 2018-2019
      location:
      content: 🐍📓➡️🌐 | SCIENTIFIC 🔬📔 BLOGGING | turn your jupyter notebook project into an educational eLibrary for next generation! 
    
# CV
cv:
  sidebar:
      about: False # set to False or comment line if you want to remove the "how to use?" in the sidebar
      education: True # set to False if you want education in main section instead of in sidebar

      # Profile information
      name: Parth Patel
      tagline: An Explorer
      avatar: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

      # Sidebar links
      email: XinYaanZyoy@astrospacetech.in
      phone: +91 815 590 3610
      website: XinYaanZyoy.github.io #do not add http://
      linkedin: XinYaanZyoy
      github: XinYaanZyoy
      telegram: # add your nickname without '@' sign
      gitlab:
      bitbucket:
      twitter: '@XinYaanZyoy'
      stack-overflow: # Number/Username, e.g. 123456/alandoe
      codewars:
      goodreads: # Number-Username, e.g. 123456-alandoe

      languages:
        - idiom: English
          level: Professional

        - idiom: Gujarati
          level: Native

        - idiom: Hindi
          level: Secondary

        - idiom: Sanskrit
          level: Elementary

        - idiom: 中文
          level: Elementary

      interests:
        - item: Archery
          link:

        - item: Cycling
          link:

        - item: Computing
          link:

  career-profile:
      title: Career Profile
      summary: |
        Summarise your career here lorem ipsum dolor sit amet, consectetuer
        adipiscing elit. You can [download this free resume/CV template here]().
        Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque
        penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        Donec quam felis, ultricies nec, pellentesque eu.
        Second paragraph if required.
  education:
      - degree: Btech in Aerospace Engineering
        university: GNA University
        time: 2017 - 2021
        details: |
          Describe your study here lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem.
            - Bullet point
            - Bullet point
      - degree: BSc in Applied Mathematics
        university: Bristol University
        time: 2007 - 2011
        details: |
          Describe your study here lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem.
            - Bullet point
            - Bullet point
  experiences:
      - role: Co-Founder
        time: 2019 - Present
        company: AstroSpaceTech
        details: |
          Describe your role here lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
          Cum sociis natoque penatibus et magnis dis parturient montes,
          nascetur ridiculus mus. Donec quam felis, ultricies nec,
          pellentesque eu, pretium quis, sem. Nulla consequat massa quis
          enim. Donec pede justo. Sed ut perspiciatis unde omnis iste natus
          error sit voluptatem accusantium doloremque laudantium, totam rem
          aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
          architecto beatae vitae dicta sunt explicabo.
            - Bullet point
            - Bullet point
      - role: Senior Software Engineer
        time: 2014 - 2015
        company: Google, London
        details: |
          Describe your role here lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
          Cum sociis natoque penatibus et magnis dis parturient montes,
          nascetur ridiculus mus. Donec quam felis, ultricies nec,
          pellentesque eu, pretium quis, sem.
            - Bullet point
            - Bullet point
      - role: UI Developer
        time: 2012 - 2014
        company: Amazon, London
        details: |
          Describe your role here lorem ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
          Cum sociis natoque penatibus et magnis dis parturient montes,
          nascetur ridiculus mus. Donec quam felis, ultricies nec,
          pellentesque eu, pretium quis, sem.
            - Bullet point
            - Bullet point
  projects:
      title: Projects
      intro: >
        You can list your side projects or open source libraries in this
        section. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Vestibulum et ligula in nunc bibendum fringilla a eu lectus.
      assignments:
        - title: Velocity
          link: "#hook"
          tagline: "A responsive website template designed to help startups promote, market and sell their products."

        - title: DevStudio
          link: "#"
          tagline: "A responsive website template designed to help web developers/designers market their services."

        - title: Tempo
          link: "#"
          tagline: "A responsive website template designed to help startups promote their products or services and to attract users &amp; investors"

        - title: Atom
          link: "#"
          tagline: "A comprehensive website template solution for startups/developers to market their mobile apps."

        - title: Delta
          link: "#"
          tagline: "A responsive Bootstrap one page theme designed to help app developers promote their mobile apps"

  publications:
      title: Publications
      intro: |
        You can list your publications in this section. Lorem ipsum dolor sit
        amet, consectetur adipiscing elit. Vestibulum et ligula in nunc
        bibendum fringilla a eu lectus.
      papers:
        - title: The Art of Computer Programming
          link: "#"
          authors: Donald E. Knuth
          conference: Addison-Wesley, 1968

        - title: "Genetic Programming III: Darwinian Invention &amp; Problem Solving"
          link: "#"
          authors: Koza, J.R., Andre, D., Bennett, F.H., Keane, M.A.
          conference: "Morgan Kaufmann Publishers Inc., San Francisco, CA, USA, 1st edn. (1999)"

        - title: A syntax directed compiler for Algol 60
          link: "#"
          authors: Edgar T. Irons
          conference: "Comm. ACM 4 (1961), 51–55"

  skills:
      title: Skills &amp; Proficiency

      toolset:
        - name: Python & Django
          level: 98%

        - name: Javascript & jQuery
          level: 98%

        - name: Angular
          level: 98%

        - name: HTML5 & CSS
          level: 95%

        - name: Ruby on Rails
          level: 85%

        - name: Sketch & Photoshop
          level: 60%

  footer: >
      Designed with <i class="fas fa-heart"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank" rel="nofollow">Xiaoying Riley</a>
    
# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
layout: default

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-books

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
