title: 心言自由(XinYaanZyoy)
logo: logo.jpeg
email: XinYaanZyoy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  👊hola!🙂
  I'm 心言自由 (XinYaanZyoy), 
  i'm A Genderless Boy; A Metaphysicist, Who Loves This Existence and Experiences Existential Crisis ALL The Time!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://XinYaanZyoy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: XinYaanZyoy
github_username:  XinYaanZyoy

collections:
  - notebooks

# Color scheme based on http://www.materialui.co/colors.
  # Possible values:
  # - default
  # - red
  # - pink
  # - brown
  # - blue
  # - purple
  # - teal
  # - green
  
  #   - type:
    #     heding:
    #     subheading:
    #     duration:
    #     location:
    #     content:
resume:
  demo: false
  photo: "https://raw.githubusercontent.com/AstroSpaceTech/AstroSpaceTech.github.io/master/assets/images/avatars/XinYaanZyoy.jpg"
  name: "Parth Patel (XinYaanZyoy)"
  copy: "I'm a metaphysicist, that is the mathematics and philosophy of metaphysical objects, also study physics, mathematics, philosophy, astronomy, computer science, technologies, and engineering!"
  color: purple
  cards:
    - type: Physics
      heading: QM
      subheading: Old Quantum theory
      duration: 2017-2018
      content: our physics mam gave me a chance to give 1.5 hrs lec on the transition from Old Quantum theory to New Quantum theory
    - type: Mathematics
      heading: Linear Algebra
      duration: 2017-2018
      subheading: A playscript on ODEs and LA
      content: i wrote this 80 pages long play script to discuss about the ODES in basic forms
    - type: Philosophy
      heading: Bhagwad Gita
      subheading: the power of gita
      content: i wrote a short note on what gives the power to gita according to my understanding
    - type: Astronomy
      heading: Start Up
      duration: 2019-present
      subheading: AstroSpacetech.in
      content: i cofounded this startup in which we write articles on Astronomy, Space Sciene, And Technologies and planning to organize events and workshops for scholl students
    - type: Computer Science.
      heading: Software Pipeline
      subheading: Xbooks
      duration: 2018-2019
      location:
      content: 🐍📓➡️🌐 | SCIENTIFIC 🔬📔 BLOGGING | turn your jupyter notebook project into an educational eLibrary for next generation! 
  footer: >
      Designed with <i class="fas fa-heart"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank" rel="nofollow">Xiaoying Riley</a>
    
# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
layout: default

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-books

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
