name: tstampupdater
on: 
  push
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: editing update timestamp
      env: 
        GH_PAT: ${{secrets.GH_PAT}}
      run: bash scripts/updatetimestamp.sh
