name: entrier

on: 
  push:
    paths: 
      - 'ebooks/md/**'
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: making an ebook
      env: 
        GH_PAT: ${{secrets.GH_PAT}}
      run: bash scripts/booker.sh
