name: diary
on: 
  push:
    paths: 
      - 'diary/**'
jobs:
  diary-entry:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: making a diary entry
      env: 
        GH_PAT: ${{secrets.GH_PAT}}
      run: bash scripts/diary.sh
  time-stamp:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: editing update timestamp
      env: 
        GH_PAT: ${{secrets.GH_PAT}}
      run: bash scripts/updatetimestamp.sh
