name: tstampupdater
on: 
  push:
    paths-ignore:
      - '_includes/header.html'
      - 'diary/**'
      - 'posts/**' 
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: editing update timestamp
      env: 
        GH_PAT: ${{secrets.GH_PAT}}
      run: bash scripts/updatetimestamp.sh
